Helpers=initHelpers(window,document);
function initHelpers(q,l,B){function u(c){(v=c)?l.querySelector("#HelperCSS")||(c=g("link",{href:"http://kooiinc.github.io/JSHelpers/Helpers.css",type:"text/css",rel:"stylesheet",id:"HelperCSS"}),l.querySelector("head").appendChild(c)):(c=document.querySelector("#HelperCSS"))&&document.querySelector("head").removeChild(c)}function w(c){if(q.jQuery)return c&&Object.ofType(c,Function)?c():!0;var d=g("script",{src:"//code.jquery.com/jquery-2.1.1.min.js",id:"jqloaded"});l.querySelector("head").appendChild(d);
c&&n(c,Function)&&d.addEventListener("load",c)}function x(){function c(){var a=h(arguments);return this.replace(/(\{\d+\})/g,function(e){return a[+e.substr(1,e.length-2)||0]})}function d(a){var e={sum:0};(a||this).map(function(a){this[a]=a in this?this[a]+1:1;this.sum+=1;return a},e);return e}if(y)return!0;String.Format=function(){var a=h(arguments);return c.apply(a[0],a.slice(1))};String.prototype.format=function(){return c.apply(this,arguments)};String.prototype.repeat=function(a){for(var e="";a--;)e+=
this;return e};Boolean.prototype.yn=function(){return 0==this?"no":"yes"};Number.prototype.toRange=Number.prototype.toRange||function(a,e){e=e||0;a=n(a,Function)?a:function(a,c){return c+e};return String(Array(this.valueOf())).split(",").map(a)};Number.prototype.pretty=Number.prototype.pretty||function(a,e){return C(this,a,e)};Function.prototype.andThen=function(){var a=h(arguments),e=a.slice(1);this();return a[0]&&e.length?a[0].andThen.apply(a[0],e):1==a.length?a[0]():!0};Function.prototype.partial=
Function.prototype.partial||function(){var a=[].slice.call(arguments),e=this;return function(){return e.apply(null,a.concat([].slice.call(arguments)))}};Function.prototype.partialx=function(){var a=this,e=Array.prototype.slice.call(arguments);return function(){for(var c=0,d=0;d<e.length&&c<arguments.length;d++)if(e[d]===B||null===e[d])e[d]=arguments[c++];return a.apply(this,e)}};String.prototype.charIsUpper=function(a){a=this.charAt(a);return/[A-Z]|[\u0080-\u024F]/.test(a)&&a===a.toUpperCase()};String.prototype.firstUp=
function(){return this.slice(0,1).toUpperCase()+this.slice(1).toLowerCase()};String.prototype.isValidEmail=function(){return/^[\w._-]{1,}[+]?[\w._-]{0,}@[\w.-]+\.[a-zA-Z]{2,6}$/.test(this)};Array.prototype.toRE=function(){try{return RegExp.apply(null,this)}catch(a){return/.*/}};Array.toRE=function(a){return[].toRE.call(a)};Array.prototype.toCheckboxValues=Array.prototype.toCheckboxValues||function(a){a=a||[];var c=[];this.map(function(d,m){c.push({check:-1<a.indexOf(m)?1:0,val:String(d)})},c);return c};
String.prototype.reCleanup=function(a){return(a?this.replace(/[\u0080-\u024F]/g,function(a){return"&#"+a.charCodeAt(0)+";"}):this).replace(/[?*|.+$\/]|\\/g,function(a){return"\\"===a?"":"\\\\"+a})};String.concat=function(a){a=a||"";return h(arguments).join(a)};Array.prototype.filter||(Array.prototype.filter=function(a){if(void 0===this||null===this)throw new TypeError;var c=Object(this),d=c.length>>>0;if(!n(a,Function))throw new TypeError;for(var m=[],h=2<=arguments.length?arguments[1]:void 0,k=0;k<
d;k++)if(k in c){var g=c[k];a.call(h,g,k,c)&&m.push(g)}return m});Array.prototype.map||(Array.prototype.map=function(a){if(void 0===this||null===this)throw new TypeError;var c=Object(this),d=c.length>>>0;if(!n(a,Function))throw new TypeError;for(var m=Array(d),g=2<=arguments.length?arguments[1]:void 0,k=0;k<d;k++)k in c&&(m[k]=a.call(g,c[k],k,c));return m});Array.prototype.uniquify=function(a){return(a||this).filter(function(a){return this[a]?!1:(this[a]=!0,!0)},{})};Array.prototype.frequencies=Array.prototype.frequencies||
d;Array.prototype.each=Array.prototype.each||function(a,c){for(var d=0;d<this.length;d++)c?this[d]=a(this[d]):a(this[d]);return this};Object.extend=function(a,c){for(var d in c)b.hasOwnProperty(d)&&(a[d]=c[d]);return a};Object.print=function(a,c){return'<pre class="code">'+JSON.stringify(a,null,c||"  ")+"</pre>"};Object.format=function(a,c){return'<div class="objformat">'+JSON.stringify(a,null,c||"  ")+"</div>"};Object.ofType=n;return y=!0}function z(){var c=l.querySelector("[data-linkid]");c&&!c.querySelector(".linkhover")&&
c.appendChild(g("div",{className:"linkhover","data-dyn":"true"}));w(function(){$("#helperload").fadeOut(900);$(document).on("mouseover",".solink",D);$(document).on("click","[data-link]",E)})}function D(c){if($(this).attr("data-link"))return!0;$.ajax({url:"http://www.nicon.nl/node/stackx/questionx",data:{qid:$(".solink").first().attr("data-linkid")},method:"post",success:function(c){c=c.items&&c.items[0]||c;var a=$(".solink").first();a.find(".linkhover").first().html("<p>Click logo to view the related question:<p><h3>"+
c.title+'</h3>Asked by <img class="profileimg" src="'+c.owner.profile_image+'"> <div data-link="'+c.owner.link+'">'+c.owner.display_name+"</div>; rep "+c.owner.reputation+"; question views: "+c.view_count);a.attr("data-link",c.link)}});return!0}function E(c){c.stopPropagation();c=this.getAttribute("data-link");var d;(d=document.querySelector('a[href="'+c+'"]'))||(c=g("a",{href:c,target:"_blank",style:{display:"none"}}),document.body.appendChild(c),d=c);d.click()}function A(){var c=document.querySelector("#result")||
function(){var a=g("div",{id:"result"});document.body.appendChild(a);return a}(),d=h(arguments),a=d.slice(-1)[0],e=/clear|clrscr|direct|opts|useopts|continuous/i,a=Object.ofType(a,Object)&&Object.keys(a).filter(function(a){return e.test(a)}).length?a.opts instanceof Object?a.opts:a:{empty:1};!a.empty&&(d=d.slice(0,-1));if(a.clrscr)return c.innerHTML="";a.clear&&(c.innerHTML="");if(a.continuous)return c.innerHTML+=d.join("").replace(/\n/g,"<br>");var f=g("p");f.innerHTML=d.join("").replace(/\n/g,"<br>").replace(/`(\b[^`]*)?`/g,
"<code>$1</code>");c.appendChild(f);return a.direct?f.className="show":setTimeout(function(){f.className="show"},1E3*+a.timed||0)}function g(c,d){var a=l.createElement(c);if(d&&n(d,Object))for(var e in d)if(d.hasOwnProperty(e))if(/style/i.test(e))for(var f in d[e])d[e].hasOwnProperty(f)&&(a.style[f]=d[e][f]);else a[e]=d[e];return a}function h(c,d){for(var a=[];a.length<c.length;)a.push(c[a.length]);return d?a.slice(d):a}function n(c){if(!c)return!1;var d=arguments.length?h(arguments).slice(1):null,
a=c.constructor;return d?!!d.filter(function(c){return c===a}).length:a.constructor.name||(String(a).match(/^function\s*([^\s(]+)/im)||[0,"ANONYMOUS_CONSTRUCTOR"])[1]}function r(c){this.initial=h(arguments,1);this.funcp=function(){return c.partialx.apply(c,this.initial)};r.prototype.x||(r.prototype.x=function(){return this.funcp().apply(null,h(arguments))})}function t(c){function d(a,c){for(var d in a)a.hasOwnProperty(d)&&(c[d]=a[d]instanceof Object?t(a[d]):a[d]);return c}return c instanceof Array?
c.slice().map(function(a){return t(a)}):c instanceof Date?new Date(c):c instanceof Object?d(c,{}):c}function C(c,d,a){function e(a,c){return String(a.toFixed(12)).split(/[.,]/)[1].substr(0,c)}var f=(""+c).split(/[.,]/),g=f[1]?f[1].length:0;c=g&&!a?e(c,g):f[1];a=d?".":",";return function(a,c){for(var d=String(a).split(""),p=-3;0<d.length+p;)d.splice(p,0,c),p-=4;return d.join("")}(f[0],d?",":".")+(f[1]?a+c:"")}var v=!1,y=x(),F={report:function(){var c=document.querySelector("#result")||function(){var a=
g("div",{id:"result"});document.querySelector("body").appendChild(a);return a}(),d=g("p");d.innerHTML=h(arguments).join("");c.appendChild(d);v&&setTimeout(function(){d.className="show"},100)},useJQ:w,useCSS:u,log2Screen:A,initSO:z,printDirect:function(){return A.apply(null,h(arguments).concat({direct:!0}))},logClear:function(){var c=l.querySelector("#result");return c&&(c.innerHTML=""),!0},Partial:r,cloneObj:t,randomID:function(){return"_"+Math.floor(1E4+1E7*Math.random()).toString(16)},extendDate:function(){Date.prototype.add||
function(){function c(a){for(var c=a.length,d={byArr:a};--c;)d[a[c]]=c;return d}function d(){this.cd=this.getDate();this.cm=this.getMonth()+1;this.cy=this.getFullYear();this.ch=this.getHours()||Number(0);this.cmin=this.getMinutes()||Number(0);this.cs=this.getSeconds()||Number(0);this.cms=this.getMilliseconds()||Number(0);this.dow=this.getDay()||Number(0)}function a(a){a=a||this;a.cy||d.call(a);var c=a.language||"EN";a={yyyy:a.cy,m:a.cm,d:a.cd,h:a.ch,min:a.cmin,s:a.cs,ms:a.cms,dow:a.dow};var c={mm:a.m.padLeft(),
dd:a.d.padLeft(),hh:a.h.padLeft(),mi:a.min.padLeft(),ss:a.s.padLeft(),mss:a.ms.padLeft(3),M:l[c].byArr[a.m-1],MM:h[c].byArr[a.m-1],wd:k[c].byArr[a.dow],WD:g[c].byArr[a.dow],WDU:g[c].byArr[a.dow].firstUp()},e=[],f;for(f in c)c.hasOwnProperty(f)&&(a[f]=c[f]);for(f in a)a.hasOwnProperty(f)&&e.push("(\\b"+f+"\\b)");a.re=new RegExp(e.join("|"),"g");return a}function e(a){var c=this+"";return(Math.pow(10,(a||2)-c.length)+c).slice(1)}var f={d:"Date",m:"Month",y:"FullYear",h:"Hours",mi:"Minutes",s:"Seconds",
ms:"MilliSeconds",get:function(a,c){return c&&"get"+this[a]||"set"+this[a]}},g={NL:c("zondag maandag dinsdag woensdag donderdag vrijdag zaterdag".split(" ")),EN:c("sunday monday tuesday wednesday thursday friday saturday".split(" "))},h={NL:c("januari februari maart april mei juni juli augustus september oktober november december".split(" ")),EN:c("january february march april may june july august september october november december".split(" "))},k={NL:c("zo ma di wo do vr za".split(" ")),EN:c("su mo tu we th fr sa".split(" "))},
l={NL:c("jan feb mrt apr mei jun jul aug sep okt nov dec".split(" ")),EN:c("jan feb mrch apr may jun jul aug sep okt nov dec".split(" "))};Number.prototype.padLeft=Number.prototype.padLeft||e;Date.prototype.setFormat=function(a){this.strformat=a;return this};Date.prototype.changeLanguage=function(a){this.language=/^[EN][NL]$/i.test(a)&&a.toUpperCase()||"NL";return this};Date.prototype.set=function(a,c){c=Number(c);c-="m"===a&&1||0;a=f.get(a);this[a](c);d.call(this);return this};Date.prototype.add=
function(a,c){if(a instanceof Object){var e;e=void 0;if(+a)e=this.setSeconds(this.getSeconds()+ +a);else{e=e&&"UTC"||"";for(var g in a){var h=g,k=+a[g],h=h&&h.slice(0,1).toUpperCase()+h.slice(1).toLowerCase()||"",h=/Fullyear/.test(h)&&"FullYear"||h;this["set"+e+h]&&this["set"+e+h](this["get"+e+h]()+k)}e=this}return e}c=Number(c)||1;e=f.get(a);g=f.get(a,1);this[e](this[g]()+c);d.call(this);return this};Date.prototype.format=function(c){c=c||this.strformat||"yyyy/mm/dd hh:mi:ss";var d=a.call(this);
return c.replace(d.re,function(a){return d[a]}).replace(/~/g,"")}}()}};/fiddle|stacksnippets/i.test(self.location.href)&&(x(),u(!0),q.addEventListener("load",function(){l.body.insertBefore(g("div",{id:"helperload"}),l.body.firstChild)}),q.addEventListener("load",z));return F};