Helpers=initHelpers(window,document);
function initHelpers(p,k,A){function t(b){(u=b)?k.querySelector("#HelperCSS")||(b=f("link",{href:"http://kooiinc.github.io/JSHelpers/Helpers.css",type:"text/css",rel:"stylesheet",id:"HelperCSS"}),k.querySelector("head").appendChild(b)):(b=document.querySelector("#HelperCSS"))&&document.querySelector("head").removeChild(b)}function v(b){if(p.jQuery)return b&&Object.ofType(b,Function)?b():!0;var c=f("script",{src:"//code.jquery.com/jquery-2.1.1.min.js",id:"jqloaded"});k.querySelector("head").appendChild(c);
b&&m(b,Function)&&c.addEventListener("load",b)}function w(){function b(){var a=g(arguments);return this.replace(/(\{\d+\})/g,function(d){return a[+d.substr(1,d.length-2)||0]})}function c(a){var d={sum:0};(a||this).map(function(a){this[a]=a in this?this[a]+1:1;this.sum+=1;return a},d);return d}if(x)return!0;String.Format=function(){var a=g(arguments);return b.apply(a[0],a.slice(1))};String.prototype.format=function(){return b.apply(this,arguments)};String.prototype.repeat=function(a){for(var d="";a--;)d+=
this;return d};Boolean.prototype.yn=function(){return 0==this?"no":"yes"};Number.prototype.toRange=Number.prototype.toRange||function(a,d){d=d||0;a=m(a,Function)?a:function(a,b){return b+d};return String(Array(this.valueOf())).split(",").map(a)};Number.prototype.pretty=Number.prototype.pretty||function(a,d){return B(this,a,d)};Function.prototype.andThen=function(){var a=g(arguments),d=a.slice(1);this();return a[0]&&d.length?a[0].andThen.apply(a[0],d):1==a.length?a[0]():!0};Function.prototype.partial=
Function.prototype.partial||function(){var a=[].slice.call(arguments),d=this;return function(){return d.apply(null,a.concat([].slice.call(arguments)))}};Function.prototype.partialx=function(){var a=this,d=Array.prototype.slice.call(arguments);return function(){for(var b=0,c=0;c<d.length&&b<arguments.length;c++)if(d[c]===A||null===d[c])d[c]=arguments[b++];return a.apply(this,d)}};String.prototype.charIsUpper=function(a){a=this.charAt(a);return/[A-Z]|[\u0080-\u024F]/.test(a)&&a===a.toUpperCase()};String.prototype.firstUp=
function(){return this.slice(0,1).toUpperCase()+this.slice(1).toLowerCase()};String.prototype.isValidEmail=function(){return/^[\w._-]{1,}[+]?[\w._-]{0,}@[\w.-]+\.[a-zA-Z]{2,6}$/.test(this)};Array.prototype.toRE=function(){try{return RegExp.apply(null,this)}catch(a){return/.*/}};Array.toRE=function(a){return[].toRE.call(a)};Array.prototype.toCheckboxValues=Array.prototype.toCheckboxValues||function(a){a=a||[];var b=[];this.map(function(c,l){b.push({check:-1<a.indexOf(l)?1:0,val:String(c)})},b);return b};
String.prototype.reCleanup=function(a){return(a?this.replace(/[\u0080-\u024F]/g,function(a){return"&#"+a.charCodeAt(0)+";"}):this).replace(/[?*|.+$\/]|\\/g,function(a){return"\\"===a?"":"\\\\"+a})};String.concat=function(a){a=a||"";return g(arguments).join(a)};Array.prototype.filter||(Array.prototype.filter=function(a){if(void 0===this||null===this)throw new TypeError;var b=Object(this),c=b.length>>>0;if(!m(a,Function))throw new TypeError;for(var l=[],g=2<=arguments.length?arguments[1]:void 0,h=0;h<
c;h++)if(h in b){var f=b[h];a.call(g,f,h,b)&&l.push(f)}return l});Array.prototype.map||(Array.prototype.map=function(a){if(void 0===this||null===this)throw new TypeError;var b=Object(this),c=b.length>>>0;if(!m(a,Function))throw new TypeError;for(var l=Array(c),f=2<=arguments.length?arguments[1]:void 0,h=0;h<c;h++)h in b&&(l[h]=a.call(f,b[h],h,b));return l});Array.prototype.uniquify=function(a){return(a||this).filter(function(a){return this[a]?!1:(this[a]=!0,!0)},{})};Array.prototype.frequencies=Array.prototype.frequencies||
c;Array.prototype.each=Array.prototype.each||function(a,b){for(var c=0;c<this.length;c++)b?this[c]=a(this[c]):a(this[c]);return this};Object.extend=function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c]);return a};Object.print=function(a,b){return'<pre class="code">'+JSON.stringify(a,null,b||"  ")+"</pre>"};Object.format=function(a,b){return'<div class="objformat">'+JSON.stringify(a,null,b||"  ")+"</div>"};Object.ofType=m;return x=!0}function y(){var b=k.querySelector("[data-linkid]");b&&!b.querySelector(".linkhover")&&
b.appendChild(f("div",{className:"linkhover","data-dyn":"true"}));v(function(){$("#helperload").fadeOut(900);$(document).on("mouseover",".solink",C);$(document).on("click","[data-link]",D)})}function C(b){if($(this).attr("data-link"))return!0;$.ajax({url:"http://www.nicon.nl/node/stackx/questionx",data:{qid:$(".solink").first().attr("data-linkid")},method:"post",success:function(b){b=b.items&&b.items[0]||b;var a=$(".solink").first();a.find(".linkhover").first().html("<p>Click logo to view the related question:<p><h3>"+
b.title+'</h3>Asked by <img class="profileimg" src="'+b.owner.profile_image+'"> <div data-link="'+b.owner.link+'">'+b.owner.display_name+"</div>; rep "+b.owner.reputation+"; question views: "+b.view_count);a.attr("data-link",b.link)}});return!0}function D(b){b.stopPropagation();b=this.getAttribute("data-link");var c;(c=document.querySelector('a[href="'+b+'"]'))||(b=f("a",{href:b,target:"_blank",style:{display:"none"}}),document.body.appendChild(b),c=b);c.click()}function z(){var b=document.querySelector("#result")||
function(){var a=f("div",{id:"result"});document.body.appendChild(a);return a}(),c=g(arguments),a=c.slice(-1)[0],d=/clear|clrscr|direct|opts|useopts|continuous/i,a=Object.ofType(a,Object)&&Object.keys(a).filter(function(a){return d.test(a)}).length?a.opts instanceof Object?a.opts:a:{empty:1};!a.empty&&(c=c.slice(0,-1));if(a.clrscr)return b.innerHTML="";a.clear&&(b.innerHTML="");if(a.continuous)return b.innerHTML+=c.join("").replace(/\n/g,"<br>");var e=f("p");e.innerHTML=c.join("").replace(/\n/g,"<br>").replace(/`(\b[^`]*)?`/g,
"<code>$1</code>");b.appendChild(e);return a.direct?e.className="show":setTimeout(function(){e.className="show"},1E3*+a.timed||0)}function f(b,c){var a=k.createElement(b);if(c&&m(c,Object))for(var d in c)if(c.hasOwnProperty(d))if(/style/i.test(d))for(var e in c[d])c[d].hasOwnProperty(e)&&(a.style[e]=c[d][e]);else a[d]=c[d];return a}function g(b,c){for(var a=[];a.length<b.length;)a.push(b[a.length]);return c?a.slice(c):a}function m(b){if(!b)return!1;var c=arguments.length?g(arguments).slice(1):null,
a=b.constructor;return c?!!c.filter(function(b){return b===a}).length:a.constructor.name||(String(a).match(/^function\s*([^\s(]+)/im)||[0,"ANONYMOUS_CONSTRUCTOR"])[1]}function q(b){this.initial=g(arguments,1);this.funcp=function(){return b.partialx.apply(b,this.initial)};q.prototype.x||(q.prototype.x=function(){return this.funcp().apply(null,g(arguments))})}function r(b){function c(a,b){for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c]instanceof Object?r(a[c]):a[c]);return b}return b instanceof Array?
b.slice().map(function(a){return r(a)}):b instanceof Date?new Date(b):b instanceof Object?c(b,{}):b}function B(b,c,a){function d(a,b){return String(a.toFixed(12)).split(/[.,]/)[1].substr(0,b)}var e=(""+b).split(/[.,]/),f=e[1]?e[1].length:0;b=f&&!a?d(b,f):e[1];a=c?".":",";return function(a,b){for(var c=String(a).split(""),n=-3;0<c.length+n;)c.splice(n,0,b),n-=4;return c.join("")}(e[0],c?",":".")+(e[1]?a+b:"")}var u=!1,x=w(),E={report:function(){var b=document.querySelector("#result")||function(){var a=
f("div",{id:"result"});document.querySelector("body").appendChild(a);return a}(),c=f("p");c.innerHTML=g(arguments).join("");b.appendChild(c);u&&setTimeout(function(){c.className="show"},100)},useJQ:v,useCSS:t,log2Screen:z,initSO:y,printDirect:function(){return z.apply(null,g(arguments).concat({direct:!0}))},logClear:function(){var b=k.querySelector("#result");return b&&(b.innerHTML=""),!0},Partial:q,cloneObj:r,randomID:function(){return"_"+Math.floor(1E4+1E7*Math.random()).toString(16)},extendDate:function(){Date.prototype.add||
function(){function b(a){for(var b=a.length,c={byArr:a};--b;)c[a[b]]=b;return c}function c(){this.cd=this.getDate();this.cm=this.getMonth()+1;this.cy=this.getFullYear();this.ch=this.getHours()||Number(0);this.cmin=this.getMinutes()||Number(0);this.cs=this.getSeconds()||Number(0);this.cms=this.getMilliseconds()||Number(0);this.dow=this.getDay()||Number(0)}function a(a){a=a||this;a.cy||c.call(a);var b=a.language||"EN";a={yyyy:a.cy,m:a.cm,d:a.cd,h:a.ch,min:a.cmin,s:a.cs,ms:a.cms,dow:a.dow};var b={mm:a.m.padLeft(),
dd:a.d.padLeft(),hh:a.h.padLeft(),mi:a.min.padLeft(),ss:a.s.padLeft(),mss:a.ms.padLeft(3),M:k[b].byArr[a.m-1],MM:g[b].byArr[a.m-1],wd:h[b].byArr[a.dow],WD:f[b].byArr[a.dow],WDU:f[b].byArr[a.dow].firstUp()},d=[],e;for(e in b)b.hasOwnProperty(e)&&(a[e]=b[e]);for(e in a)a.hasOwnProperty(e)&&d.push("(\\b"+e+"\\b)");a.re=new RegExp(d.join("|"),"g");return a}function d(a){var b=this+"";return(Math.pow(10,(a||2)-b.length)+b).slice(1)}var e={d:"Date",m:"Month",y:"FullYear",h:"Hours",mi:"Minutes",s:"Seconds",
ms:"MilliSeconds",get:function(a,b){return b&&"get"+this[a]||"set"+this[a]}},f={NL:b("zondag maandag dinsdag woensdag donderdag vrijdag zaterdag".split(" ")),EN:b("sunday monday tuesday wednesday thursday friday saturday".split(" "))},g={NL:b("januari februari maart april mei juni juli augustus september oktober november december".split(" ")),EN:b("january february march april may june july august september october november december".split(" "))},h={NL:b("zo ma di wo do vr za".split(" ")),EN:b("su mo tu we th fr sa".split(" "))},
k={NL:b("jan feb mrt apr mei jun jul aug sep okt nov dec".split(" ")),EN:b("jan feb mrch apr may jun jul aug sep okt nov dec".split(" "))};Number.prototype.padLeft=Number.prototype.padLeft||d;Date.prototype.setFormat=function(a){this.strformat=a;return this};Date.prototype.changeLanguage=function(a){this.language=/^[EN][NL]$/i.test(a)&&a.toUpperCase()||"NL";return this};Date.prototype.set=function(a,b){b=Number(b);b-="m"===a&&1||0;a=e.get(a);this[a](b);c.call(this);return this};Date.prototype.add=
function(a,b){if(a instanceof Object){var d;d=void 0;if(+a)d=this.setSeconds(this.getSeconds()+ +a);else{d=d&&"UTC"||"";for(var f in a){var g=f,h=+a[f],g=g&&g.slice(0,1).toUpperCase()+g.slice(1).toLowerCase()||"",g=/Fullyear/.test(g)&&"FullYear"||g;this["set"+d+g]&&this["set"+d+g](this["get"+d+g]()+h)}d=this}return d}b=Number(b)||1;d=e.get(a);f=e.get(a,1);this[d](this[f]()+b);c.call(this);return this};Date.prototype.format=function(b){b=b||this.strformat||"yyyy/mm/dd hh:mi:ss";var c=a.call(this);
return b.replace(c.re,function(a){return c[a]}).replace(/~/g,"")}}()}};/fiddle|stacksnippets/i.test(self.location.href)&&(w(),t(!0),p.addEventListener("load",function(){k.body.insertBefore(f("div",{id:"helperload"}),k.body.firstChild)}),p.addEventListener("load",y));return E};